include_recipe 'mo_monitoring_client::_reqs'
include_recipe 'mo_monitoring_client::basic'
include_recipe 'mo_monitoring_client::fpm'
include_recipe 'mo_monitoring_client::mail'
include_recipe 'mo_monitoring_client::nginx'
include_recipe 'mo_monitoring_client::mysql'
